version: "3.9"
services:
  at:
    container_name: at
    build:
      context: scraper
    environment:
      - geckodriver=/usr/local/bin/geckodriver
      - spring.datasource.url=jdbc:mysql://mysql_db:3306/at_database
    ports:
      - "8080:8080"
    volumes:
      - ./ArticleTracker/at:/data
    networks:
      - at-network
    command: tail -f /dev/null
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: at_database
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - at-network

networks:
  at-network:
    driver: bridge
