version: "3.9"
services:
  jenkins:
    build:
      context: ./jenkins
    environment:
      - geckodriver=/usr/local/bin/geckodriver
      - MAILER_SMTP_HOST=mailhog
      - MAILER_SMTP_PORT=1025
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      - devtools-network
    depends_on:
      - sonarqube
      - mailhog

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/temp:/opt/sonarqube/temp
    networks:
      - devtools-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - devtools-network

networks:
  devtools-network:
    driver: bridge
